waldo-rails-app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "images#new"
  
  resource :session
  resources :passwords, param: :token


  resources :users, only: [:new, :create, :edit]
  resources :images, only: [:new, :create, :show]

  namespace :api do
    resource :session, only: [:create, :show, :destroy]
    resources :users, only: [:create]
    resources :passwords, param: :token, only: [:create, :update]
  end

end

waldo-rails-app/app/models/image.rb
class Image < ApplicationRecord
  has_many :characters, inverse_of: :image, dependent: :destroy
  accepts_nested_attributes_for :characters, allow_destroy: true

  validates :title, presence: true, length: { minimum: 3, maximum: 40 }
  validates :image, presence: true

  has_one_attached :image
end

waldo-rails-app/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  allow_unauthenticated_access
  
  def show
    @image = Image.find(params[:id])
    respond_to do |format|
      format.json { render json: @image }
      format.html { render :show }
    end
  end

  def new
    @image = Image.new
    @character = @image.characters.build
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to @image
    else
      render :new
    end
  end

  private

  def image_params
    params.require(:image).permit(
      :image, :title,
      characters_attributes: [:id, :name, :start_x, :end_x, :start_y, :end_y]
      )
  end
end

waldo-rails-app/app/views/images/_character_fields.html.erb
<div class="character-fields" data-new-image-target="characterFields"
  data-character-index="<%= char_fields.index %>">
  <%= char_fields.label :name, "Character Name" %>
  <%= char_fields.text_field :name %>
  <%= char_fields.label :start_x %>
  <%= char_fields.number_field :start_x, step: 0.001 %>
  <%= char_fields.label :end_x %>
  <%= char_fields.number_field :end_x, step: 0.001 %>
  <%= char_fields.label :start_y %>
  <%= char_fields.number_field :start_y, step: 0.001 %>
  <%= char_fields.label :end_y %>
  <%= char_fields.number_field :end_y, step: 0.001 %>
  <button
    type="button"
    class="remove-character-btn"
    data-action="click->new-image#removeCharacter"
  >Remove</button>
</div>

waldo-rails-app/app/views/images/new.html.erb
<h1>New Image</h1>

<% if @image.errors.any? %>
  <ul>
    <% @image.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
  
<%= form_with model: @image, url: images_path, method: :post,
  data: { controller: "new-image" } do |image_form| %>
  <%= image_form.label :url, "Upload Image" %>
  <%= image_form.file_field :image %>
  <%= image_form.label :title %>
  <%= image_form.text_field :title %>
  
  <h3>Characters</h3>
  <div id="characters-fields" data-new-image-target="charactersFields">
    <%= image_form.fields_for :characters do |char_fields| %>
      <%= render('character_fields', char_fields: char_fields) %>
    <% end %>
  </div>

  <!-- Template for new character fields -->
  <template id="character-fields-template" data-new-image-target="characterFieldsTemplate">
    <%= image_form.fields_for :characters, Character.new, child_index: "NEW_RECORD" do |char_fields| %>
      <%= render('character_fields', char_fields: char_fields) %>
    <% end %>
  </template>

  <button
    type="button"
    data-new-image-target="addCharacter"
    id="add-character-btn"
    data-action="click->new-image#addCharacter"
  >+</button>
  
  <%= image_form.submit "Create Image" %>
<% end %>

waldo-rails-app/app/views/images/show.html.erb
<h1>Image title - <span id="image-title"><%= @image.title %></span></h1>
<ul>
  <% @image.characters.each do |character| %>
    <li>
      name: <%= character.name %> |
      start_x: <%= character.start_x %> |
      end_x: <%= character.end_x %> |
      start_y: <%= character.start_y %> |
      end_y: <%= character.end_y %> |
    </li>
  <% end %>
</ul>
<div id="image-container">
  <%= image_tag @image.image, alt: @image.title %>
  
  <% @image.characters.each do |character| %>

    <div
      id="character-<%= character.id %>-<%= character.name %>"
      class="character-marker"
      style="
        position: absolute;
        left: <%= (character.start_x * 100)  %>%;
        top: <%= character.start_y * 100 %>%;
        width: <%= (character.end_x - character.start_x) * 100 %>%;
        height: <%= (character.end_y - character.start_y) * 100 %>%;
        border: 4px solid red;
        padding: 4px;
        background-color: rgba(0, 0, 0, 0.2);
    "><span><%= character.name %></span>
    </div>

  <% end %>

</div>